// <auto-generated />
using System;
using AlocacaoVeic.Repositorio.Contexto;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace AlocacaoVeic.Repositorio.Migrations
{
    [DbContext(typeof(AlocacaoContext))]
    [Migration("20200429221725_Alocacao Inicial")]
    partial class AlocacaoInicial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("AlocacaoVeic.Dominio.Entidades.Alocacao", b =>
                {
                    b.Property<int>("idAlocacao")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("FormaPagto");

                    b.Property<int>("PagtoID");

                    b.Property<int>("UsuarioID");

                    b.Property<int>("VeiculoID");

                    b.Property<DateTime>("dtFim");

                    b.Property<DateTime>("dtInicio");

                    b.HasKey("idAlocacao");

                    b.HasIndex("UsuarioID");

                    b.HasIndex("VeiculoID");

                    b.ToTable("Alocacoes");
                });

            modelBuilder.Entity("AlocacaoVeic.Dominio.Entidades.Cliente", b =>
                {
                    b.Property<int>("idCliente")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("enuSEXO");

                    b.Property<string>("strEmail")
                        .IsRequired()
                        .HasMaxLength(50);

                    b.Property<string>("strNmCliente")
                        .IsRequired()
                        .HasMaxLength(50);

                    b.HasKey("idCliente");

                    b.ToTable("Clientes");
                });

            modelBuilder.Entity("AlocacaoVeic.Dominio.Entidades.Usuario", b =>
                {
                    b.Property<int>("idUser")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool>("booADMIN");

                    b.Property<string>("strEmail")
                        .IsRequired()
                        .HasMaxLength(50);

                    b.Property<string>("strNmUsuario")
                        .IsRequired()
                        .HasMaxLength(50);

                    b.Property<string>("strSenha")
                        .IsRequired()
                        .HasMaxLength(400);

                    b.HasKey("idUser");

                    b.ToTable("Usuarios");
                });

            modelBuilder.Entity("AlocacaoVeic.Dominio.Entidades.Veiculo", b =>
                {
                    b.Property<int>("idVeiculo")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<double>("douPreco")
                        .HasColumnType("float");

                    b.Property<string>("strModelo")
                        .IsRequired()
                        .HasMaxLength(400);

                    b.Property<string>("strNomeArq");

                    b.Property<string>("strPlaca")
                        .IsRequired()
                        .HasMaxLength(50);

                    b.HasKey("idVeiculo");

                    b.ToTable("Veiculos");
                });

            modelBuilder.Entity("AlocacaoVeic.Dominio.Entidades.Alocacao", b =>
                {
                    b.HasOne("AlocacaoVeic.Dominio.Entidades.Usuario", "Usuario")
                        .WithMany("Alocacoes")
                        .HasForeignKey("UsuarioID")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("AlocacaoVeic.Dominio.Entidades.Veiculo", "Veiculo")
                        .WithMany()
                        .HasForeignKey("VeiculoID")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
